### ISSUE TITLE
Not working with Firefox?

### ISSUE THREAD

**Issue by wvdongen** [malerisch/burp-csj#6]
First of all great job on this plugin!

When I send a URL to Crawljax with Firefox set, Firefox just starts up with no address in the address bar. With Chrome and chrome driver it works fine. How can I get it working with Firefox?

**Comment by malerisch** [comment]
Hi there,

Thanks and glad you like it. The issue you highlight is known (see: https://code.google.com/p/selenium/issues/detail?id=7642) and it appears to be a bug in Selenium. I am tracking this in Crawljax github: https://github.com/crawljax/crawljax/issues/443
Once a new crawljax package which fixes the issue is available, I will update BurpCSJ.

**Comment by malerisch** [comment]
This issue has been fixed with Crawjlax 3.6. New BurpCSJ jar available: bit.ly/burpcsj0-3

**Comment by ruiper** [comment]
I have just tried to use FF with the latest BurpCSJ (-3) and am still getting the behavior originally described here. FF starts up with no URL and the FF windows is almost immediately closed. With BurpCSJ (-2) at least the FF window hung around a bit before auto-closing.

**Comment by malerisch** [comment]
Are you using BurpCSJ from BAppStore? If yes, I have the same issue.

Try to manually add this Jar from my site and use that one instead: http://bit.ly/burpcsj0-3

It works fine for me with FF 34.0.5 (Win7).

Cheers,

Roberto

**Comment by malerisch** [comment]
This issue is fixed also in BAppStore.

**Comment by ruiper** [comment]
Unfortunately, with FF 41 (Win7) I am still getting the problem described above (FF starts, stays around for a few seconds, disappears)
